package com.alerts.strategies;

import com.alerts.Alert;
import com.data_management.Patient;
import java.util.List;

/** Strategy interface for patient-data alert checks. */
public interface AlertStrategy {
    /**
     * Checks one patient and returns all alerts generated by this strategy.
     *
     * @param patient patient to evaluate
     * @return generated alerts
     */
    List<Alert> checkAlert(Patient patient);
}