package com.alerts;

/**
 * Common interface for all alerts generated by the monitoring system.
 *
 * <p>Project Part 4 requires decorators to implement the same Alert abstraction that they wrap.
 * Therefore Alert is an interface and concrete alerts provide the actual stored data.</p>
 */
public interface Alert {
    /** @return patient identifier as a String */
    String getPatientId();

    /** @return medical condition that caused the alert */
    String getCondition();

    /** @return timestamp at which the alert was generated */
    long getTimestamp();

    /**
     * Returns the alert category. Decorators delegate this value to the wrapped alert.
     *
     * @return alert type/category
     */
    default String getAlertType() {
        return "Generic";
    }

    /**
     * Returns the priority label. Base alerts are normal priority unless decorated.
     *
     * @return priority label
     */
    default String getPriority() {
        return "NORMAL";
    }

    /**
     * Indicates whether this alert should be re-checked/repeated.
     *
     * @return true for repeated alerts
     */
    default boolean isRepeated() {
        return false;
    }

    /**
     * Returns the repeat interval in milliseconds. Non-repeated alerts return 0.
     *
     * @return repeat interval in milliseconds
     */
    default long getRepeatIntervalMillis() {
        return 0L;
    }
}